select * from table Customer where FirstName like 'L%A'
OR FirstName like 'L%B'
OR FirstName like 'L%C'
OR FirstName like 'L%D'
OR FirstName like 'J%A'
OR FirstName like 'J%B'
OR FirstName like 'J%C'
OR FirstName like 'J%D'
OR FirstName like 'I%A'
OR FirstName like 'I%B'
OR FirstName like 'I%C'
OR FirstName like 'I%D'
OR FirstName like 'S%A'
OR FirstName like 'S%B'
OR FirstName like 'S%C'
OR FirstName like 'S%D'